### ISSUE TITLE
Phantom 1.9.0-6 cannot be installed

### ISSUE THREAD

**Issue by jjmr** [mattgoldspink/grunt-sencha-dependencies#40]
Npm dependency of Phantomjs with version 1.9.0-6 tries to download the binary from an unexistent url (an out of date url of googlecode). 
To solve this problem, phantomjs version should be increased in the package.json of the gtunt-sencha-dependencies.

**Comment by andrei-ivanov** [comment]
Same problem here...
Seems that this project is abandoned :-(

**Comment by mattgoldspink** [comment]
@jjmr @andrei-ivanov Hey guys - the project isn't completely abandoned! However I don't use it any more since I'm not doing any Sencha dev work. However I'd be more than happy to accept any pull requests that fix this, so feel free to submit one and I'll merge and update the project.

**Comment by andrei-ivanov** [comment]
@mattgoldspink That's good news :)
I've just started working with these technologies on a project that's in maintenance mode and I ran into this issue.
Since I cannot upgrade to the latest versions (PhantomJS 2.x), I thought of just upgrading the deps to the latest 1.9 versions available.
I hope it's fine.

**Comment by andrei-ivanov** [comment]
I've sent the PR, not sure if you've been notified :)

**Comment by andrei-ivanov** [comment]
@mattgoldspink hello?

**Comment by mattgoldspink** [comment]
HI @andrei-ivanov - Sorry for the delay. You caught me in the middle of 36 hours of flights. I'll aim to take a look at merging and updating npm over the weekend for you.

**Comment by andrei-ivanov** [comment]
@mattgoldspink Great :)

**Comment by mattgoldspink** [comment]
@andrei-ivanov version 0.9.0 is now available with this fix on NPM - https://www.npmjs.com/package/grunt-sencha-dependencies

**Comment by andrei-ivanov** [comment]
@mattgoldspink that is awesome, I can confirm it is working now :-)
Thank you very much.
